openapi: 3.0.0
info:
  title: Threat Intelligence API
  version: 1.0.0
  description: Public API for retrieving and analyzing threat intelligence data

paths:
  /threats:
    get:
      summary: Retrieve all stored threats
      responses:
        '200':
          description: A list of threats
          content:
            application/json:
              example:
                - id: 1
                  source: "Shodan"
                  ip: "8.8.8.8"
                  data: {...}
                  timestamp: "2025-04-10T12:00:00Z"

  /analyze:
    post:
      summary: Analyze a threat using AI
      requestBody:
        required: true
        content:
          application/json:
            example:
              threat: "SQL Injection"
              likelihood: 4
              impact: 5
      responses:
        '200':
          description: AI risk assessment
          content:
            application/json:
              example:
                threat: "SQL Injection"
                likelihood: 4
                impact: 5
                ai_assessment: "High risk due to high likelihood and impact."
